# Generated by Django 4.2.5 on 2024-02-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_default_role"),
    ]

    operations = [
        # migrations.AddIndex(
        #     model_name="filmwork",
        #     index=models.Index(fields=["creation_date"], name="film_work_creation_date_idx"),
        # ),
        # migrations.AddIndex(
        #     model_name="filmwork",
        #     index=models.Index(fields=["rating"], name="film_work_rating_idx"),
        # ),
        # migrations.AddIndex(
        #     model_name="filmwork",
        #     index=models.Index(fields=["title"], name="film_work_title_idx"),
        # ),
        # migrations.AddIndex(
        #     model_name="filmwork",
        #     index=models.Index(fields=["rating", "creation_date"], name="film_work_rating_creation_idx"),
        # ),
        # migrations.AddIndex(
        #     model_name="genre",
        #     index=models.Index(fields=["name"], name="genre_name_idx"),
        # ),
        # migrations.AddIndex(
        #     model_name="genrefilmwork",
        #     index=models.Index(fields=["film_work", "genre"], name="film_work_genre_idx"),
        # ),
        # migrations.AddIndex(
        #     model_name="person",
        #     index=models.Index(fields=["full_name"], name="person_full_name_idx"),
        # ),
        # migrations.AddIndex(
        #     model_name="personfilmwork",
        #     index=models.Index(fields=["film_work", "person"], name="film_work_person_idx"),
        # ),
    ]
